[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/sync.html"
  to = "/sync.html"
  status = 200

[[redirects]]
  from = "/hub.html"
  to = "/hub.html"
  status = 200
